global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "esppd_app"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["host.docker.internal:8000"] # Assuming Octane exposes metrics or using a package

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
